### ISSUE TITLE
No artifacts found 

### ISSUE THREAD

**Issue by joepio** [tauri-apps/tauri-action#196]
Hi there, thanks for creating and maintaining this.

I'm trying to get my action to create the bundles, but for some reason, after building, [I get](https://github.com/joepio/atomic-data-rust/runs/4485737207?check_suite_focus=true#step:7:767):

`Error: No artifacts were found. `

However, right before this it seems like artifacts were correctly built:

```
     Finished 2 bundles at:
        /Users/runner/work/atomic-data-rust/atomic-data-rust/target/release/bundle/macos/Atomic Server.app
        /Users/runner/work/atomic-data-rust/atomic-data-rust/target/release/bundle/dmg/Atomic Server_0.28.2_x64.dmg
```

[github action](https://github.com/joepio/atomic-data-rust/blob/c889f04e687836ce557d4a63cce0338ae51fdef1/.github/workflows/tauri-publish.yml)

Any ideas on how to solve this?

**Comment by lucasfernog** [comment]
Will try it tonight.

**Comment by joepio** [comment]
Thanks for the quick fix @lucasfernog 

I tried running it again, but a new problem was introduced ([see action](https://github.com/joepio/atomic-data-rust/runs/4492465153?check_suite_focus=true))

```
/home/runner/work/_actions/tauri-apps/tauri-action/8e430cc7b0fab28f0a7768f2157933c94f8724f6/packages/action/dist/index.js:1
import{createRequire as __WEBPACK_EXTERNAL_createRequire}from"module";var __webpack_modules__={9548:function(e,t,r){var s=this&&this.__createBinding||(Object.create?function(e,t,r,s){if(s===undefined)s=r;Object.defineProperty(e,s,{enumerable:true,get:function(){return t[r]}})}:function(e,t,r,s){if(s===undefined)s=r;e[s]=t[r]});var n=this&&this.__setModuleDefault||(Object.create?function(e,t){Object.defineProperty(e,"default",{enumerable:true,value:t})}:function(e,t){e["default"]=t});var o=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(e!=null)for(var r in e)if(r!=="default"&&Object.hasOwnProperty.call(e,r))s(t,e,r);n(t,e);return t};Object.defineProperty(t,"__esModule",{value:true});t.issue=t.issueCommand=void 0;const i=o(r(2037));const a=r(7472);function issueCommand(e,t,r){const s=new Command(e,t,r);process.stdout.write(s.toString()+i.EOL)}t.issueCommand=

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by lucasfernog** [comment]
Try again after #201 @joepio

**Comment by joepio** [comment]
Yes! it works :D

Thank you very much :)
