### ISSUE TITLE
tauri-build: unknown field `tsp`

### ISSUE THREAD

**Issue by jeff-hykin** [tauri-apps/tauri-action#242]
(mentioned in #147 but #147 is about a different issue)

Ran
`cargo install tauri-cli --version 1.0.0-rc.7`

But still encountered the issue :/

Cargo/Rust `cargo 1.61.0-nightly (65c826642 2022-03-09)`

<img width="1620" alt="Screen Shot 2022-03-14 at 3 36 35 PM" src="https://user-images.githubusercontent.com/17692058/158257613-8523e206-e625-4bfe-b7bf-46fd67226bd4.png">

Here's the text from the image.
```


   Compiling tauri-utils v1.0.0-rc.3
   Compiling tauri-bundler v1.0.0-rc.3
   Compiling tauri-cli v1.0.0-rc.7
    Finished release [optimized] target(s) in 8m 54s
   Replacing /Users/jeffhykin/repos/testing-tauri/settings/home/.cargo/bin/cargo-tauri
    Replaced package `tauri-cli v1.0.0-rc.7 (https://github.com/tauri-apps/tauri/?rev=4c84559e1f3019e7aa2666b10a1a0bd97bb09d24#4c84559e)` with `tauri-cli v1.0.0-rc.7` (executable `cargo-tauri`)

Graviton-App on  main via 𝗥 v1.61.0 took 8m 54s 
∫ yarn dev_desktop                            
yarn run v1.22.10
$ jake dev_web_components dev_desktop
Starting 'dev_web_components'...
Finished 'dev_web_components' after 6 ms
Starting 'dev_desktop'...
[tauri:dev] Running `yarn --cwd ../web run dev`
[tauri:dev] Waiting for your frontend dev server to start on http://localhost:8080/...
$ tsc && vite build --watch
$ vite

  vite v2.7.10 dev server running at:

  > Local: http://localhost:8080/
  > Network: use `--host` to expose

  ready in 1841ms.

   Compiling gveditor-core-deno v0.1.0 (/Users/jeffhykin/repos/testing-tauri/Graviton-App/core_deno)
   Compiling git2 v0.13.25
   Compiling graviton v0.1.0 (/Users/jeffhykin/repos/testing-tauri/Graviton-App/desktop/src-tauri)
error: failed to run custom build command for `graviton v0.1.0 (/Users/jeffhykin/repos/testing-tauri/Graviton-App/desktop/src-tauri)`

Caused by:
  process didn't exit successfully: `/Users/jeffhykin/repos/testing-tauri/target.ignore/debug/build/graviton-5f99b6ae7c6779cd/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=tauri.conf.json

  --- stderr
  thread 'main' panicked at 'error found during tauri-build: unknown field `tsp`, expected one of `digestAlgorithm`, `certificateThumbprint`, `timestampUrl`, `webviewFixedRuntimePath`, `wix` at line 1 column 924', /Users/jeffhykin/repos/testing-tauri/settings/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-build-1.0.0-rc.3/src/lib.rs:146:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/core/src/panicking.rs:143:14
     2: tauri_build::build
               at /Users/jeffhykin/repos/testing-tauri/settings/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-build-1.0.0-rc.3/src/lib.rs:146:5
     3: build_script_build::main
               at ./src/build.rs:2:5
     4: core::ops::function::FnOnce::call_once
               at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
    Building [=======================> ] 681/685: git2                                                                                                                                                                                            
Found 0 errors. Watching for file changes.
```

**Comment by FabianLars** [comment]
You need to update tauri and tauri-build in Cargo.toml to 1.0.0-rc.4

**Comment by jeff-hykin** [comment]
Okay, I'll let the people at Gravitron know!
Updating was tested and does indeed work (Thank you @FabianLars)
