### ISSUE TITLE
Syntax error: Unexpected number

### ISSUE THREAD

**Issue by viridia** [tauri-apps/tauri-action#283]
I'm trying to integrate the tauri-action into my github project, and I'm getting this error:

```
SyntaxError: Unexpected number
    at new AsyncFunction (<anonymous>)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4807:16)
    at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4862:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4846:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:[24](https://github.com/viridia/vortex/runs/7056129164?check_suite_focus=true#step:5:25):31)
    at startup (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:52:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Error: Unhandled error: SyntaxError: Unexpected number
```

I'm not sure how to debug this, I'm not that familiar with github actions.

Here's the workflow https://github.com/viridia/vortex/runs/7056129164?check_suite_focus=true#step:5:33

And here's the workflow definition file, which is mostly a copy and paste from the example: https://github.com/viridia/vortex/blob/main/.github/workflows/artifacts.yml

**Comment by thegame4craft** [comment]
I getting this error too.

**Comment by boywithkeyboard** [comment]
Your script is invalid. It should be valid JavaScript code.

@viridia, to make your workflow work, you need to change the following:

```diff
- tag_name: vortex-v${{ env.PACKAGE_VERSION }},
- name: "Vortex v${{ env.PACKAGE_VERSION }}",
+ tag_name: `vortex-v${process.env.PACKAGE_VERSION}`,
+ name: `Vortex v${process.env.PACKAGE_VERSION}`,
```

You can learn more [here](https://github.com/actions/github-script).

**Comment by viridia** [comment]
That appears to work.

I should note, however, that I simply copy/pasted from your example in the README which has the same syntax.
